#!/usr/bin/env bash
# AIngle Developer Setup Script
# Version: 2.0.0
# One-command setup for AIngle development environment

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
RUST_MIN_VERSION="1.70.0"
WASM_TARGET="wasm32-unknown-unknown"

print_banner() {
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║                                                           ║"
    echo "║     █████╗ ██╗███╗   ██╗ ██████╗ ██╗     ███████╗        ║"
    echo "║    ██╔══██╗██║████╗  ██║██╔════╝ ██║     ██╔════╝        ║"
    echo "║    ███████║██║██╔██╗ ██║██║  ███╗██║     █████╗          ║"
    echo "║    ██╔══██║██║██║╚██╗██║██║   ██║██║     ██╔══╝          ║"
    echo "║    ██║  ██║██║██║ ╚████║╚██████╔╝███████╗███████╗        ║"
    echo "║    ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝╚══════╝        ║"
    echo "║                                                           ║"
    echo "║         Semantic DAG for IoT & AI Applications           ║"
    echo "║                    Developer Setup                        ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

version_gte() {
    [ "$(printf '%s\n' "$1" "$2" | sort -V | head -n1)" = "$2" ]
}

check_rust() {
    log_info "Checking Rust installation..."

    if ! check_command rustc; then
        log_error "Rust not found. Installing via rustup..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
    fi

    local rust_version=$(rustc --version | cut -d' ' -f2)
    if version_gte "$rust_version" "$RUST_MIN_VERSION"; then
        log_success "Rust $rust_version (>= $RUST_MIN_VERSION required)"
    else
        log_warn "Rust $rust_version found, but >= $RUST_MIN_VERSION required"
        log_info "Updating Rust..."
        rustup update stable
    fi
}

check_wasm_target() {
    log_info "Checking WASM target..."

    if rustup target list --installed | grep -q "$WASM_TARGET"; then
        log_success "WASM target installed: $WASM_TARGET"
    else
        log_info "Installing WASM target..."
        rustup target add "$WASM_TARGET"
        log_success "WASM target installed"
    fi
}

check_system_deps() {
    log_info "Checking system dependencies..."

    local missing_deps=()

    # Check for common dependencies
    if ! check_command cmake; then
        missing_deps+=("cmake")
    fi

    if ! check_command pkg-config; then
        missing_deps+=("pkg-config")
    fi

    if [[ ${#missing_deps[@]} -gt 0 ]]; then
        log_warn "Missing dependencies: ${missing_deps[*]}"

        if [[ "$OSTYPE" == "darwin"* ]]; then
            if check_command brew; then
                log_info "Installing via Homebrew..."
                brew install "${missing_deps[@]}"
            else
                log_error "Please install Homebrew and run: brew install ${missing_deps[*]}"
                exit 1
            fi
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            log_info "Installing via apt..."
            sudo apt-get update
            sudo apt-get install -y "${missing_deps[@]}"
        else
            log_error "Please install: ${missing_deps[*]}"
            exit 1
        fi
    else
        log_success "All system dependencies present"
    fi
}

setup_env() {
    log_info "Setting up environment variables..."

    local env_file=".env.local"

    if [[ ! -f "$env_file" ]]; then
        cat > "$env_file" << 'EOF'
# AIngle Development Environment
# Generated by setup.sh

# IoT Mode: Set to 0 for sub-second confirmation
# Default: 5000 (5 seconds) for backwards compatibility
AINGLE_PUBLISH_INTERVAL_MS=5000

# Logging
RUST_LOG=info,aingle=debug,kitsune_p2p=debug

# Network tuning for local development
AINGLE_GOSSIP_LOOP_ITERATION_DELAY_MS=1000
AINGLE_GOSSIP_PEER_ON_SUCCESS_NEXT_GOSSIP_DELAY_MS=60000

# Database
AINGLE_DB_PATH=./data

# Conductor admin port (default)
AINGLE_ADMIN_PORT=9000
EOF
        log_success "Created $env_file"
    else
        log_success "Environment file exists: $env_file"
    fi
}

setup_iot_mode() {
    log_info "Setting up IoT mode configuration..."

    local iot_env_file=".env.iot"

    cat > "$iot_env_file" << 'EOF'
# AIngle IoT Mode Environment
# Optimized for sub-second confirmation and low-power devices

# Sub-second confirmation (critical for IoT)
AINGLE_PUBLISH_INTERVAL_MS=0

# Aggressive gossip for fast propagation
AINGLE_GOSSIP_LOOP_ITERATION_DELAY_MS=100
AINGLE_GOSSIP_PEER_ON_SUCCESS_NEXT_GOSSIP_DELAY_MS=5000
AINGLE_GOSSIP_PEER_ON_ERROR_NEXT_GOSSIP_DELAY_MS=30000
AINGLE_GOSSIP_OUTPUT_TARGET_MBPS=10.0

# Minimal logging for performance
RUST_LOG=warn,aingle=info

# Memory optimization
AINGLE_MEMORY_LIMIT_MB=256
EOF
    log_success "Created $iot_env_file (use with: source .env.iot)"
}

build_project() {
    log_info "Building AIngle..."

    local build_mode="${1:-debug}"

    if [[ "$build_mode" == "release" ]]; then
        log_info "Building in release mode (this may take a while)..."
        cargo build --release
    else
        log_info "Building in debug mode..."
        cargo build
    fi

    log_success "Build completed"
}

run_tests() {
    log_info "Running tests..."
    cargo test --workspace --lib
    log_success "Tests passed"
}

print_help() {
    echo "Usage: ./setup.sh [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --full        Full setup with build and tests"
    echo "  --deps-only   Only check/install dependencies"
    echo "  --build       Build the project (debug mode)"
    echo "  --release     Build in release mode"
    echo "  --test        Run tests"
    echo "  --iot         Setup IoT mode configuration"
    echo "  --help        Show this help message"
    echo ""
    echo "Environment:"
    echo "  After setup, source .env.local for development"
    echo "  For IoT mode: source .env.iot"
}

print_next_steps() {
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}                    Setup Complete!                         ${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Load environment:"
    echo -e "     ${CYAN}source .env.local${NC}"
    echo ""
    echo "  2. Build the project:"
    echo -e "     ${CYAN}cargo build${NC}"
    echo ""
    echo "  3. Run tests:"
    echo -e "     ${CYAN}cargo test --workspace${NC}"
    echo ""
    echo "  4. Start a node:"
    echo -e "     ${CYAN}cargo run --bin aingle${NC}"
    echo ""
    echo "For IoT mode (sub-second confirmation):"
    echo -e "     ${CYAN}source .env.iot && cargo run --bin aingle${NC}"
    echo ""
    echo "Documentation: https://github.com/AIngleLab/aingle"
    echo ""
}

main() {
    print_banner

    local full_setup=false
    local deps_only=false
    local do_build=false
    local release_mode=false
    local do_test=false
    local iot_mode=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --full)
                full_setup=true
                shift
                ;;
            --deps-only)
                deps_only=true
                shift
                ;;
            --build)
                do_build=true
                shift
                ;;
            --release)
                release_mode=true
                do_build=true
                shift
                ;;
            --test)
                do_test=true
                shift
                ;;
            --iot)
                iot_mode=true
                shift
                ;;
            --help|-h)
                print_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                print_help
                exit 1
                ;;
        esac
    done

    # Default: full setup if no options
    if [[ "$full_setup" == "false" && "$deps_only" == "false" && "$do_build" == "false" && "$do_test" == "false" && "$iot_mode" == "false" ]]; then
        full_setup=true
    fi

    # Always check deps
    check_rust
    check_wasm_target
    check_system_deps

    if [[ "$deps_only" == "true" ]]; then
        log_success "Dependencies check complete"
        exit 0
    fi

    # Setup environment
    setup_env

    if [[ "$iot_mode" == "true" ]]; then
        setup_iot_mode
    fi

    # Build
    if [[ "$full_setup" == "true" || "$do_build" == "true" ]]; then
        if [[ "$release_mode" == "true" ]]; then
            build_project "release"
        else
            build_project "debug"
        fi
    fi

    # Test
    if [[ "$full_setup" == "true" || "$do_test" == "true" ]]; then
        run_tests
    fi

    print_next_steps
}

main "$@"
